### ISSUE TITLE
Eureka - Reducir tiempos de registro y descubrimiento al arrancar el servidor y los procesos [ZAH-163]

### ISSUE THREAD

**Issue by zahori-io** [zahori-io/eureka-server#17]
Hay que reducir los tiempos de registro y descubrimiento al arrancar el servidor y los procesos.

@davidvazqu3z ha intentado realizarlo vía configuración de Eureka y no ha obtenido resultados positivos.
@davidvazqu3z va a sustituir Eureka por Consul

**Comment by davidvazqu3z** [comment]
Posible solución a probar: reemplazar Eureka por Consul

**Comment by davidvazqu3z** [comment]
Reducidos los tiempos de registro y descubrimiento al arrancar el proceso reemplazando Eureka por Consul.
